# See: https://help.github.com/en/actions/reference/software-installed-on-github-hosted-runners
# 2020-06-22 - slg - customized
# 2020-06-27 - slg - expanded to G++ for MacOS
# 2020-07-03 - slg - ported to be13_api; removed python (be13_api doesn't use python)

name: BE13_API CI (c++17)
on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['macos-10.15','ubuntu-20.04' ]

    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install MacOS dependencies
        if: startsWith(matrix.os, 'macos')
        run: |
          brew install autoconf automake libtool

      - name: Install Ubuntu dependencies
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt install -y libtool autoconf automake libssl-dev pkg-config

      - name: Update autoconf on Ubuntu
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          wget https://ftpmirror.gnu.org/autoconf/autoconf-2.71.tar.gz
          tar xfz autoconf-2.71.tar.gz && cd autoconf-2.71 && ./configure && make && sudo make install

      - name: Update automake on Ubuntu
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          wget https://ftpmirror.gnu.org/automake/automake-1.16.3.tar.gz
          tar xfz automake-1.16.3.tar.gz && cd automake-1.16.3 && ./configure && make && sudo make install

      - name: run bootstrap
        run: |
          bash bootstrap.sh

      - name: configure for ubuntu
        if: startsWith(matrix.os, 'ubuntu')
        # it seems that -fsanitize=address and -fsanitize=memory fail under Catch2 with Ubuntu
        run: |
          ./configure CXXFLAGS='-g -O0 -fprofile-arcs -ftest-coverage ' LIBS='-lgcov'

      - name: configure for macOS
        if: startsWith(matrix.os, 'macos')
        # it seems that -fsanitize=address and -fsanitize=memory breaks C++17 under GitHub Actions/MacOS
        run: |
          ./configure

      - name: make check
        run: |
          make test_be13_api
          ./test_be13_api
          make check  || (for fn in test*.log ; do echo ""; echo $fn ; cat $fn ; done; exit 1)

      - uses: ammaraskar/gcc-problem-matcher@0.1
        name: GCC Problem Matcher

      - name: upload codecov report
        if: startsWith(matrix.os, 'ubuntu')
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          gcov-9 -o . `find . -name '*cpp'`
          bash <(curl -s https://codecov.io/bash)
